import Foundation

/// Loads merchants.json (bundled package resource, generated by
/// scripts/build_merchants.js in the main repo) once and keeps it in
/// memory. Mirrors lib/services/merchant_repository.dart.
public final class MerchantRepository {
    public static let shared = MerchantRepository()

    private var merchants: [Merchant] = []
    private var isLoaded = false

    public init() {}

    /// Call once, same timing as RewardRulesRepository.load(). Idempotent.
    public func load() throws {
        guard !isLoaded else { return }

        guard let url = Bundle.module.url(forResource: "merchants", withExtension: "json") else {
            throw RewardRulesRepositoryError.resourceNotFound("merchants")
        }
        let data = try Data(contentsOf: url)
        merchants = try JSONDecoder().decode([Merchant].self, from: data)
        isLoaded = true
    }

    public func all() -> [Merchant] {
        merchants
    }
}
