import Foundation

public enum RewardRulesRepositoryError: Error {
    case resourceNotFound(String)
}

/// Loads cube_reward_rules.json / jiho_reward_rules.json (bundled package
/// resources, generated by scripts/convert_allen_rewards.js in the main
/// repo — re-run that script and copy the two files here whenever Allen
/// supplies a new crawl export) once and keeps them in memory, keyed by
/// cardId. Mirrors lib/services/reward_rules_repository.dart.
public final class RewardRulesRepository {
    public static let shared = RewardRulesRepository()

    private var rulesByCard: [String: [CardRewardRule]] = [:]
    private var isLoaded = false

    private static let ruleFileNames = ["cube_reward_rules", "jiho_reward_rules"]

    public init() {}

    /// Call once — e.g. in your App's init(), or an async task before the
    /// first screen appears — before using rulesFor()/allRules() or any
    /// evaluator/RecommendationOrchestrator call. Idempotent.
    public func load() throws {
        guard !isLoaded else { return }

        let decoder = JSONDecoder()
        for fileName in Self.ruleFileNames {
            guard let url = Bundle.module.url(forResource: fileName, withExtension: "json") else {
                throw RewardRulesRepositoryError.resourceNotFound(fileName)
            }
            let data = try Data(contentsOf: url)
            let rules = try decoder.decode([CardRewardRule].self, from: data)
            for rule in rules {
                rulesByCard[rule.cardId, default: []].append(rule)
            }
        }

        isLoaded = true
    }

    public func rulesFor(_ cardId: String) -> [CardRewardRule] {
        rulesByCard[cardId] ?? []
    }

    public func allRules() -> [CardRewardRule] {
        rulesByCard.values.flatMap { $0 }
    }
}
