-- 這個檔案是產生出來的，不要手動編輯。
-- 來源：lib/data/merchants.json（452 家商家）
-- 重新產生：node scripts/mysql/build_merchants_sql.js

USE credit_card_app;

-- 先清子表再清主表（外鍵順序）；整批取代，對齊 merchants.json
DELETE FROM merchant_aliases;
DELETE FROM merchant_tags;
DELETE FROM merchants;

INSERT INTO merchants
  (merchant_id, canonical_name, display_name, primary_category, subcategory, channel, country, active)
VALUES
  ('m_10mois台灣官網', '10mois台灣官網', '10mois台灣官網', 'retail', NULL, 'offline', 'TW', 1),
  ('m_55688', '55688', '55688', 'travel', NULL, 'offline', 'TW', 1),
  ('m_7_eleven', '7-ELEVEN', '7-ELEVEN', 'convenience_store', NULL, 'offline', 'JP', 1),
  ('m_7_eleven_7_11_實體門市', '7-ELEVEN (7-11) 實體門市', '7-ELEVEN (7-11) 實體門市', 'convenience_store', NULL, 'offline', 'TW', 1),
  ('m_一風堂', '一風堂', '一風堂', 'dining', NULL, 'offline', 'TW', 1),
  ('m_九族文化村', '九族文化村', '九族文化村', 'theme_park', NULL, 'offline', 'TW', 1),
  ('m_二本松涮涮屋', '二本松涮涮屋', '二本松涮涮屋', 'dining', NULL, 'offline', 'TW', 1),
  ('m_三井outlet', '三井OUTLET', '三井OUTLET', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_三友藥妝tomod_s', '三友藥妝Tomod\'s', '三友藥妝Tomod\'s', 'drugstore', NULL, 'offline', 'TW', 1),
  ('m_三賀旅行社', '三賀旅行社', '三賀旅行社', 'travel', NULL, 'offline', 'TW', 1),
  ('m_三越', '三越', '三越', 'department_store', NULL, 'offline', 'JP', 1),
  ('m_三點三', '三點三', '三點三', 'dining', NULL, 'offline', 'TW', 1),
  ('m_久碳吉炭火燒肉', '久碳吉炭火燒肉', '久碳吉炭火燒肉', 'dining', NULL, 'offline', 'TW', 1),
  ('m_千葉火鍋', '千葉火鍋', '千葉火鍋', 'dining', NULL, 'offline', 'TW', 1),
  ('m_土耳其航空', '土耳其航空', '土耳其航空', 'travel', NULL, 'offline', 'TW', 1),
  ('m_大戶屋', '大戶屋', '大戶屋', 'dining', NULL, 'offline', 'TW', 1),
  ('m_大全聯', '大全聯', '大全聯', 'supermarket', NULL, 'offline', 'TW', 1),
  ('m_大江國際購物中心', '大江國際購物中心', '大江國際購物中心', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_大阪環球影城', '大阪環球影城', '大阪環球影城', 'theme_park', NULL, 'offline', 'JP', 1),
  ('m_大河屋_燒肉丼_串燒', '大河屋 燒肉丼 串燒', '大河屋 燒肉丼 串燒', 'dining', NULL, 'offline', 'TW', 1),
  ('m_大溪笠復威斯汀度假酒店', '大溪笠復威斯汀度假酒店', '大溪笠復威斯汀度假酒店', 'hotel', NULL, 'offline', 'TW', 1),
  ('m_大葉高島屋', '大葉高島屋', '大葉高島屋', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_大樹先生的家', '大樹先生的家', '大樹先生的家', 'retail', NULL, 'offline', 'TW', 1),
  ('m_大韓航空', '大韓航空', '大韓航空', 'travel', NULL, 'offline', 'TW', 1),
  ('m_小方舟串燒酒場', '小方舟串燒酒場', '小方舟串燒酒場', 'dining', NULL, 'offline', 'TW', 1),
  ('m_小叮噹科學園區主題樂園', '小叮噹科學園區主題樂園', '小叮噹科學園區主題樂園', 'theme_park', NULL, 'offline', 'TW', 1),
  ('m_小米台灣', '小米台灣', '小米台灣', 'retail', NULL, 'offline', 'TW', 1),
  ('m_小島3_5度親子餐廳', '小島3.5度親子餐廳', '小島3.5度親子餐廳', 'retail', NULL, 'offline', 'TW', 1),
  ('m_小樹購', '小樹購', '小樹購', 'digital', NULL, 'offline', 'TW', 1),
  ('m_山富旅遊', '山富旅遊', '山富旅遊', 'travel', NULL, 'offline', 'TW', 1),
  ('m_中友百貨', '中友百貨', '中友百貨', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_中華航空', '中華航空', '中華航空', 'travel', NULL, 'offline', 'TW', 1),
  ('m_五福旅遊', '五福旅遊', '五福旅遊', 'travel', NULL, 'offline', 'TW', 1),
  ('m_六福村主題樂園', '六福村主題樂園', '六福村主題樂園', 'theme_park', NULL, 'offline', 'TW', 1),
  ('m_六福莊', '六福莊', '六福莊', 'hotel', NULL, 'offline', 'TW', 1),
  ('m_天吉屋', '天吉屋', '天吉屋', 'dining', NULL, 'offline', 'TW', 1),
  ('m_天貓', '天貓', '天貓', 'digital', NULL, 'offline', 'TW', 1),
  ('m_太平洋百貨', '太平洋百貨', '太平洋百貨', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_屯京拉麵', '屯京拉麵', '屯京拉麵', 'dining', NULL, 'offline', 'TW', 1),
  ('m_巴哈姆特動畫瘋', '巴哈姆特動畫瘋', '巴哈姆特動畫瘋', 'dining', NULL, 'offline', 'TW', 1),
  ('m_日本航空', '日本航空', '日本航空', 'travel', NULL, 'offline', 'TW', 1),
  ('m_日本橋浜町食事处', '日本橋浜町食事处', '日本橋浜町食事处', 'dining', NULL, 'offline', 'TW', 1),
  ('m_日藥本舖', '日藥本舖', '日藥本舖', 'drugstore', NULL, 'offline', 'TW', 1),
  ('m_毛丼丼飯專門店', '毛丼丼飯專門店', '毛丼丼飯專門店', 'dining', NULL, 'offline', 'TW', 1),
  ('m_毛房蔥柚鍋_冷藏肉專門', '毛房蔥柚鍋．冷藏肉專門', '毛房蔥柚鍋．冷藏肉專門', 'dining', NULL, 'offline', 'TW', 1),
  ('m_毛蔬亞洲蔬食', '毛蔬亞洲蔬食', '毛蔬亞洲蔬食', 'dining', NULL, 'offline', 'TW', 1),
  ('m_水鳥和洋創作料理', '水鳥和洋創作料理', '水鳥和洋創作料理', 'dining', NULL, 'offline', 'TW', 1),
  ('m_火火燒肉販賣所', '火火燒肉販賣所', '火火燒肉販賣所', 'dining', NULL, 'offline', 'TW', 1),
  ('m_加利利旅行社', '加利利旅行社', '加利利旅行社', 'travel', NULL, 'offline', 'TW', 1),
  ('m_卡多摩', '卡多摩', '卡多摩', 'retail', NULL, 'offline', 'TW', 1),
  ('m_卡多摩嬰童館', '卡多摩嬰童館', '卡多摩嬰童館', 'retail', NULL, 'offline', 'TW', 1),
  ('m_卡達航空', '卡達航空', '卡達航空', 'travel', NULL, 'offline', 'TW', 1),
  ('m_古北町台灣官網', '古北町台灣官網', '古北町台灣官網', 'retail', NULL, 'offline', 'TW', 1),
  ('m_可樂旅遊', '可樂旅遊', '可樂旅遊', 'travel', NULL, 'offline', 'TW', 1),
  ('m_台中漢神洲際購物廣場', '台中漢神洲際購物廣場', '台中漢神洲際購物廣場', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_台北101', '台北101', '台北101', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_台北市私立道明外僑學校', '台北市私立道明外僑學校', '台北市私立道明外僑學校', 'education', NULL, 'offline', 'TW', 1),
  ('m_台北私立立人國際國小', '台北私立立人國際國小', '台北私立立人國際國小', 'education', NULL, 'offline', 'TW', 1),
  ('m_台北美國學校', '台北美國學校', '台北美國學校', 'education', NULL, 'offline', 'TW', 1),
  ('m_台北喜來登大飯店', '台北喜來登大飯店', '台北喜來登大飯店', 'hotel', NULL, 'offline', 'TW', 1),
  ('m_台北歐洲學校', '台北歐洲學校', '台北歐洲學校', 'education', NULL, 'offline', 'TW', 1),
  ('m_台亞加油站', '台亞加油站', '台亞加油站', 'gas_station', NULL, 'offline', 'TW', 1),
  ('m_台南晶英酒店', '台南晶英酒店', '台南晶英酒店', 'hotel', NULL, 'offline', 'TW', 1),
  ('m_台茂購物中心', '台茂購物中心', '台茂購物中心', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_台塑生醫實體門市', '台塑生醫實體門市', '台塑生醫實體門市', 'retail', NULL, 'offline', 'TW', 1),
  ('m_台塑石油加油站', '台塑石油加油站', '台塑石油加油站', 'gas_station', NULL, 'offline', 'TW', 1),
  ('m_台塑蔬菜實體門市', '台塑蔬菜實體門市', '台塑蔬菜實體門市', 'supermarket', NULL, 'offline', 'TW', 1),
  ('m_台塑購物網', '台塑購物網', '台塑購物網', 'digital', NULL, 'offline', 'TW', 1),
  ('m_台鐵', '台鐵', '台鐵', 'travel', NULL, 'offline', 'TW', 1),
  ('m_台灣大車隊', '台灣大車隊', '台灣大車隊', 'travel', NULL, 'offline', 'TW', 1),
  ('m_台灣中油', '台灣中油', '台灣中油', 'gas_station', NULL, 'offline', 'TW', 1),
  ('m_台灣中油_直營站', '台灣中油-直營站', '台灣中油-直營站', 'gas_station', NULL, 'offline', 'TW', 1),
  ('m_台灣虎航', '台灣虎航', '台灣虎航', 'travel', NULL, 'offline', 'TW', 1),
  ('m_台灣高鐵', '台灣高鐵', '台灣高鐵', 'travel', NULL, 'offline', 'TW', 1),
  ('m_台灣壽司郎', '台灣壽司郎', '台灣壽司郎', 'dining', NULL, 'offline', 'TW', 1),
  ('m_巧虎夢想樂園', '巧虎夢想樂園', '巧虎夢想樂園', 'theme_park', NULL, 'offline', 'TW', 1),
  ('m_札幌藥妝', '札幌藥妝', '札幌藥妝', 'drugstore', NULL, 'offline', 'TW', 1),
  ('m_永利旅行社', '永利旅行社', '永利旅行社', 'travel', NULL, 'offline', 'TW', 1),
  ('m_永旺', '永旺', '永旺', 'department_store', NULL, 'offline', 'JP', 1),
  ('m_立秋_li_chiu', '立秋 Li Chiu', '立秋 Li Chiu', 'dining', NULL, 'offline', 'TW', 1),
  ('m_全家便利商店_實體門市', '全家便利商店 實體門市', '全家便利商店 實體門市', 'convenience_store', NULL, 'offline', 'TW', 1),
  ('m_全國電子', '全國電子', '全國電子', 'retail', NULL, 'offline', 'TW', 1),
  ('m_全球迪士尼飯店', '全球迪士尼飯店', '全球迪士尼飯店', 'hotel', NULL, 'offline', 'TW', 1),
  ('m_全聯福利中心', '全聯福利中心', '全聯福利中心', 'supermarket', NULL, 'offline', 'TW', 1),
  ('m_全聯福利中心_實體門市', '全聯福利中心 實體門市', '全聯福利中心 實體門市', 'supermarket', NULL, 'offline', 'TW', 1),
  ('m_吉天麩羅', '吉天麩羅', '吉天麩羅', 'dining', NULL, 'offline', 'TW', 1),
  ('m_吉豚屋', '吉豚屋', '吉豚屋', 'dining', NULL, 'offline', 'TW', 1),
  ('m_好樂迪ktv', '好樂迪KTV', '好樂迪KTV', 'entertainment', NULL, 'offline', 'TW', 1),
  ('m_好嶼_hosu', '好嶼 HOSU', '好嶼 HOSU', 'dining', NULL, 'offline', 'TW', 1),
  ('m_安琪兒婦嬰百貨', '安琪兒婦嬰百貨', '安琪兒婦嬰百貨', 'retail', NULL, 'offline', 'TW', 1),
  ('m_有你真好湘菜沙龍', '有你真好湘菜沙龍', '有你真好湘菜沙龍', 'dining', NULL, 'offline', 'TW', 1),
  ('m_朱宗慶打擊樂教學系統', '朱宗慶打擊樂教學系統', '朱宗慶打擊樂教學系統', 'education', NULL, 'offline', 'TW', 1),
  ('m_汐游寶寶', '汐游寶寶', '汐游寶寶', 'education', NULL, 'offline', 'TW', 1),
  ('m_肉料理福', '肉料理福', '肉料理福', 'dining', NULL, 'offline', 'TW', 1),
  ('m_你家樓下', '你家樓下', '你家樓下', 'dining', NULL, 'offline', 'TW', 1),
  ('m_宏匯廣場', '宏匯廣場', '宏匯廣場', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_找到了旅行社', '找到了旅行社', '找到了旅行社', 'travel', NULL, 'offline', 'TW', 1),
  ('m_杏一藥局', '杏一藥局', '杏一藥局', 'drugstore', NULL, 'offline', 'TW', 1),
  ('m_秀泰生活', '秀泰生活', '秀泰生活', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_車麻吉', '車麻吉', '車麻吉', 'mobility', NULL, 'offline', 'TW', 1),
  ('m_亞洲航空', '亞洲航空', '亞洲航空', 'travel', NULL, 'offline', 'TW', 1),
  ('m_享千葉火鍋', '享千葉火鍋', '享千葉火鍋', 'dining', NULL, 'offline', 'TW', 1),
  ('m_享溫馨ktv', '享溫馨KTV', '享溫馨KTV', 'entertainment', NULL, 'offline', 'TW', 1),
  ('m_京丘炭火燒鳥專門店', '京丘炭火燒鳥專門店', '京丘炭火燒鳥專門店', 'dining', NULL, 'offline', 'TW', 1),
  ('m_京丘燒鳥酒処', '京丘燒鳥酒処', '京丘燒鳥酒処', 'dining', NULL, 'offline', 'TW', 1),
  ('m_京站', '京站', '京站', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_和逸飯店', '和逸飯店', '和逸飯店', 'hotel', NULL, 'offline', 'TW', 1),
  ('m_和運租車', '和運租車', '和運租車', 'travel', NULL, 'offline', 'TW', 1),
  ('m_定食8', '定食8', '定食8', 'dining', NULL, 'offline', 'TW', 1),
  ('m_宜兒樂', '宜兒樂', '宜兒樂', 'retail', NULL, 'offline', 'TW', 1),
  ('m_宜蘭礁溪鳳凰酒店', '宜蘭礁溪鳳凰酒店', '宜蘭礁溪鳳凰酒店', 'hotel', NULL, 'offline', 'TW', 1),
  ('m_屈臣氏', '屈臣氏', '屈臣氏', 'drugstore', NULL, 'offline', 'TW', 1),
  ('m_所_suo', '所 SUO', '所 SUO', 'dining', NULL, 'offline', 'TW', 1),
  ('m_拓元售票', '拓元售票', '拓元售票', 'digital', NULL, 'offline', 'TW', 1),
  ('m_昇恆昌', '昇恆昌', '昇恆昌', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_東京迪士尼', '東京迪士尼', '東京迪士尼', 'theme_park', NULL, 'offline', 'JP', 1),
  ('m_東京華納兄弟哈利波特影城', '東京華納兄弟哈利波特影城', '東京華納兄弟哈利波特影城', 'theme_park', NULL, 'offline', 'TW', 1),
  ('m_東南旅遊', '東南旅遊', '東南旅遊', 'travel', NULL, 'offline', 'TW', 1),
  ('m_東橫inn', '東橫INN', '東橫INN', 'hotel', NULL, 'offline', 'TW', 1),
  ('m_松本清', '松本清', '松本清', 'drugstore', NULL, 'offline', 'TW', 1),
  ('m_欣葉日本料理', '欣葉日本料理', '欣葉日本料理', 'dining', NULL, 'offline', 'TW', 1),
  ('m_欣葉日本料理_彩膳楽亭', '欣葉日本料理 彩膳楽亭', '欣葉日本料理 彩膳楽亭', 'dining', NULL, 'offline', 'TW', 1),
  ('m_法國的秘密甜點', '法國的秘密甜點', '法國的秘密甜點', 'dining', NULL, 'offline', 'TW', 1),
  ('m_法國航空', '法國航空', '法國航空', 'travel', NULL, 'offline', 'TW', 1),
  ('m_芮秋_rachel', '芮秋 Rachel', '芮秋 Rachel', 'dining', NULL, 'offline', 'TW', 1),
  ('m_花蓮遠雄悅來大飯店', '花蓮遠雄悅來大飯店', '花蓮遠雄悅來大飯店', 'hotel', NULL, 'offline', 'TW', 1),
  ('m_金子半之助', '金子半之助', '金子半之助', 'dining', NULL, 'offline', 'TW', 1),
  ('m_長汎假期', '長汎假期', '長汎假期', 'travel', NULL, 'offline', 'TW', 1),
  ('m_長庚生技實體門市', '長庚生技實體門市', '長庚生技實體門市', 'retail', NULL, 'offline', 'TW', 1),
  ('m_長榮航空', '長榮航空', '長榮航空', 'travel', NULL, 'offline', 'TW', 1),
  ('m_阿聯酋航空', '阿聯酋航空', '阿聯酋航空', 'travel', NULL, 'offline', 'TW', 1),
  ('m_青沐', '青沐', '青沐', 'dining', NULL, 'offline', 'TW', 1),
  ('m_俏媽咪', '俏媽咪', '俏媽咪', 'retail', NULL, 'offline', 'TW', 1),
  ('m_南紡購物中心', '南紡購物中心', '南紡購物中心', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_威秀影城', '威秀影城', '威秀影城', 'entertainment', NULL, 'offline', 'TW', 1),
  ('m_思夢樂', '思夢樂', '思夢樂', 'retail', NULL, 'offline', 'TW', 1),
  ('m_星宇航空', '星宇航空', '星宇航空', 'travel', NULL, 'offline', 'TW', 1),
  ('m_星野集團', '星野集團', '星野集團', 'hotel', NULL, 'offline', 'TW', 1),
  ('m_星聚點ktv', '星聚點KTV', '星聚點KTV', 'entertainment', NULL, 'offline', 'TW', 1),
  ('m_春囍打邊爐', '春囍打邊爐', '春囍打邊爐', 'dining', NULL, 'offline', 'TW', 1),
  ('m_祇園_禪院壽喜燒', '祇園.禪院壽喜燒', '祇園.禪院壽喜燒', 'dining', NULL, 'offline', 'TW', 1),
  ('m_美麗華', '美麗華', '美麗華', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_耐斯廣場', '耐斯廣場', '耐斯廣場', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_唐吉訶德', '唐吉訶德', '唐吉訶德', 'retail', NULL, 'offline', 'JP', 1),
  ('m_家樂福', '家樂福', '家樂福', 'supermarket', NULL, 'offline', 'TW', 1),
  ('m_格上租車', '格上租車', '格上租車', 'travel', NULL, 'offline', 'TW', 1),
  ('m_桃園名人堂花園大飯店', '桃園名人堂花園大飯店', '桃園名人堂花園大飯店', 'hotel', NULL, 'offline', 'TW', 1),
  ('m_特力屋', '特力屋', '特力屋', 'retail', NULL, 'offline', 'TW', 1),
  ('m_特斯拉', '特斯拉', '特斯拉', 'mobility', NULL, 'offline', 'TW', 1),
  ('m_馬禮遜學校', '馬禮遜學校', '馬禮遜學校', 'education', NULL, 'offline', 'TW', 1),
  ('m_高島屋', '高島屋', '高島屋', 'department_store', NULL, 'offline', 'JP', 1),
  ('m_高雄美國學校', '高雄美國學校', '高雄美國學校', 'education', NULL, 'offline', 'TW', 1),
  ('m_高雄萬豪酒店', '高雄萬豪酒店', '高雄萬豪酒店', 'hotel', NULL, 'offline', 'TW', 1),
  ('m_高鐵', '高鐵', '高鐵', 'travel', NULL, 'offline', 'TW', 1),
  ('m_做茶菜', '做茶菜', '做茶菜', 'dining', NULL, 'offline', 'TW', 1),
  ('m_國內餐飲', '國內餐飲', '國內餐飲', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_國泰航空', '國泰航空', '國泰航空', 'travel', NULL, 'offline', 'TW', 1),
  ('m_國賓影城', '國賓影城', '國賓影城', 'entertainment', NULL, 'offline', 'TW', 1),
  ('m_康乃薾美國學校', '康乃薾美國學校', '康乃薾美國學校', 'education', NULL, 'offline', 'TW', 1),
  ('m_康是美', '康是美', '康是美', 'drugstore', NULL, 'offline', 'TW', 1),
  ('m_康橋國際學校', '康橋國際學校', '康橋國際學校', 'education', NULL, 'offline', 'TW', 1),
  ('m_捷星航空', '捷星航空', '捷星航空', 'travel', NULL, 'offline', 'TW', 1),
  ('m_涮乃葉', '涮乃葉', '涮乃葉', 'dining', NULL, 'offline', 'TW', 1),
  ('m_涮之華', '涮之華', '涮之華', 'dining', NULL, 'offline', 'TW', 1),
  ('m_淘寶', '淘寶', '淘寶', 'digital', NULL, 'offline', 'TW', 1),
  ('m_淘寶網', '淘寶網', '淘寶網', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_理想旅遊', '理想旅遊', '理想旅遊', 'travel', NULL, 'offline', 'TW', 1),
  ('m_陳阿姨火鍋灶咖', '陳阿姨火鍋灶咖', '陳阿姨火鍋灶咖', 'dining', NULL, 'offline', 'TW', 1),
  ('m_陶板屋', '陶板屋', '陶板屋', 'dining', NULL, 'offline', 'TW', 1),
  ('m_髙_gao_taipei', '髙 GAO Taipei', '髙 GAO Taipei', 'dining', NULL, 'offline', 'TW', 1),
  ('m_鳥苑_torien_yakitori', '鳥苑 Torien Yakitori', '鳥苑 Torien Yakitori', 'dining', NULL, 'offline', 'TW', 1),
  ('m_麥當勞', '麥當勞', '麥當勞', 'dining', NULL, 'offline', 'TW', 1),
  ('m_勝博殿', '勝博殿', '勝博殿', 'dining', NULL, 'offline', 'TW', 1),
  ('m_喜鴻假期', '喜鴻假期', '喜鴻假期', 'travel', NULL, 'offline', 'TW', 1),
  ('m_嵐山熟成牛_專売', '嵐山熟成牛かつ專売-', '嵐山熟成牛かつ專売-', 'dining', NULL, 'offline', 'TW', 1),
  ('m_復興實驗高中', '復興實驗高中', '復興實驗高中', 'education', NULL, 'offline', 'TW', 1),
  ('m_竣師父牛肉麵', '竣師父牛肉麵', '竣師父牛肉麵', 'dining', NULL, 'offline', 'TW', 1),
  ('m_粥起粥底火鍋熱炒', '粥起粥底火鍋熱炒', '粥起粥底火鍋熱炒', 'dining', NULL, 'offline', 'TW', 1),
  ('m_統一時代台北店', '統一時代台北店', '統一時代台北店', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_統一時代百貨', '統一時代百貨', '統一時代百貨', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_統一速邁樂加油站', '統一速邁樂加油站', '統一速邁樂加油站', 'gas_station', NULL, 'offline', 'TW', 1),
  ('m_華泰名品城', '華泰名品城', '華泰名品城', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_華盛頓小學', '華盛頓小學', '華盛頓小學', 'education', NULL, 'offline', 'TW', 1),
  ('m_萊爾富實體門市', '萊爾富實體門市', '萊爾富實體門市', 'convenience_store', NULL, 'offline', 'TW', 1),
  ('m_越捷航空', '越捷航空', '越捷航空', 'travel', NULL, 'offline', 'TW', 1),
  ('m_雄獅旅遊', '雄獅旅遊', '雄獅旅遊', 'travel', NULL, 'offline', 'TW', 1),
  ('m_雲門舞集舞蹈教室', '雲門舞集舞蹈教室', '雲門舞集舞蹈教室', 'education', NULL, 'offline', 'TW', 1),
  ('m_雲品溫泉酒店', '雲品溫泉酒店', '雲品溫泉酒店', 'hotel', NULL, 'offline', 'TW', 1),
  ('m_媽咪愛', '媽咪愛', '媽咪愛', 'retail', NULL, 'offline', 'TW', 1),
  ('m_媽媽好', '媽媽好', '媽媽好', 'retail', NULL, 'offline', 'TW', 1),
  ('m_嵩_sung', '嵩 sung', '嵩 sung', 'dining', NULL, 'offline', 'TW', 1),
  ('m_微風百貨', '微風百貨', '微風百貨', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_微風廣場', '微風廣場', '微風廣場', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_新千葉火鍋', '新千葉火鍋', '新千葉火鍋', 'dining', NULL, 'offline', 'TW', 1),
  ('m_新月廣場', '新月廣場', '新月廣場', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_新加坡航空', '新加坡航空', '新加坡航空', 'travel', NULL, 'offline', 'TW', 1),
  ('m_新光三越', '新光三越', '新光三越', 'dining', NULL, 'offline', 'TW', 1),
  ('m_新光三越百貨', '新光三越百貨', '新光三越百貨', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_新光影城', '新光影城', '新光影城', 'entertainment', NULL, 'offline', 'TW', 1),
  ('m_新宿內臟燒肉', '新宿內臟燒肉', '新宿內臟燒肉', 'dining', NULL, 'offline', 'TW', 1),
  ('m_極千葉火鍋', '極千葉火鍋', '極千葉火鍋', 'dining', NULL, 'offline', 'TW', 1),
  ('m_煙波大飯店新竹湖濱館', '煙波大飯店新竹湖濱館', '煙波大飯店新竹湖濱館', 'hotel', NULL, 'offline', 'TW', 1),
  ('m_瑞穗天合國際觀光酒店', '瑞穗天合國際觀光酒店', '瑞穗天合國際觀光酒店', 'hotel', NULL, 'offline', 'TW', 1),
  ('m_萬家福_樂家康', '萬家福/樂家康', '萬家福/樂家康', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_義大皇家酒店', '義大皇家酒店', '義大皇家酒店', 'hotel', NULL, 'offline', 'TW', 1),
  ('m_義大遊樂世界', '義大遊樂世界', '義大遊樂世界', 'theme_park', NULL, 'offline', 'TW', 1),
  ('m_蜀叔麻辣鍋', '蜀叔麻辣鍋', '蜀叔麻辣鍋', 'dining', NULL, 'offline', 'TW', 1),
  ('m_誠品生活', '誠品生活', '誠品生活', 'retail', NULL, 'offline', 'TW', 1),
  ('m_達美航空', '達美航空', '達美航空', 'travel', NULL, 'offline', 'TW', 1),
  ('m_壽司美登利', '壽司美登利', '壽司美登利', 'dining', NULL, 'offline', 'TW', 1),
  ('m_壽司涮乃葉', '壽司涮乃葉', '壽司涮乃葉', 'dining', NULL, 'offline', 'TW', 1),
  ('m_夢時代', '夢時代', '夢時代', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_漢神巨蛋', '漢神巨蛋', '漢神巨蛋', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_漢神百貨', '漢神百貨', '漢神百貨', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_福懋加油站', '福懋加油站', '福懋加油站', 'gas_station', NULL, 'offline', 'TW', 1),
  ('m_維多利亞雙語中小學', '維多利亞雙語中小學', '維多利亞雙語中小學', 'education', NULL, 'offline', 'TW', 1),
  ('m_遠東百貨', '遠東百貨', '遠東百貨', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_遠東garden_city', '遠東Garden City', '遠東Garden City', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_遠東sogo', '遠東SOGO', '遠東SOGO', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_遠東sogo百貨', '遠東SOGO百貨', '遠東SOGO百貨', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_酷航', '酷航', '酷航', 'travel', NULL, 'offline', 'TW', 1),
  ('m_銀杏中餐廳', '銀杏中餐廳', '銀杏中餐廳', 'dining', NULL, 'offline', 'TW', 1),
  ('m_鳳凰旅行社', '鳳凰旅行社', '鳳凰旅行社', 'travel', NULL, 'offline', 'TW', 1),
  ('m_鳳凰旅遊', '鳳凰旅遊', '鳳凰旅遊', 'travel', NULL, 'offline', 'TW', 1),
  ('m_劍湖山世界主題樂園', '劍湖山世界主題樂園', '劍湖山世界主題樂園', 'theme_park', NULL, 'offline', 'TW', 1),
  ('m_廣三sogo', '廣三SOGO', '廣三SOGO', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_樂兒屋', '樂兒屋', '樂兒屋', 'retail', NULL, 'offline', 'TW', 1),
  ('m_樂桃航空', '樂桃航空', '樂桃航空', 'travel', NULL, 'offline', 'TW', 1),
  ('m_樂麵屋', '樂麵屋', '樂麵屋', 'dining', NULL, 'offline', 'TW', 1),
  ('m_澄居烤物燒肉', '澄居烤物燒肉', '澄居烤物燒肉', 'dining', NULL, 'offline', 'TW', 1),
  ('m_稻鎮經典台灣菜', '稻鎮經典台灣菜', '稻鎮經典台灣菜', 'dining', NULL, 'offline', 'TW', 1),
  ('m_蝦皮購物', '蝦皮購物', '蝦皮購物', 'digital', NULL, 'offline', 'TW', 1),
  ('m_輝室', '輝室', '輝室', 'dining', NULL, 'offline', 'TW', 1),
  ('m_墾丁凱撒大飯店', '墾丁凱撒大飯店', '墾丁凱撒大飯店', 'hotel', NULL, 'offline', 'TW', 1),
  ('m_橋山壽喜燒', '橋山壽喜燒', '橋山壽喜燒', 'dining', NULL, 'offline', 'TW', 1),
  ('m_燒肉smile', '燒肉Smile', '燒肉Smile', 'dining', NULL, 'offline', 'TW', 1),
  ('m_燒鳩', '燒鳩', '燒鳩', 'dining', NULL, 'offline', 'TW', 1),
  ('m_錢櫃ktv', '錢櫃KTV', '錢櫃KTV', 'entertainment', NULL, 'offline', 'TW', 1),
  ('m_澀_sur', '澀 Sur-', '澀 Sur-', 'dining', NULL, 'offline', 'TW', 1),
  ('m_燦坤', '燦坤', '燦坤', 'retail', NULL, 'offline', 'TW', 1),
  ('m_燦星旅遊', '燦星旅遊', '燦星旅遊', 'travel', NULL, 'offline', 'TW', 1),
  ('m_環球購物中心', '環球購物中心', '環球購物中心', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_礁溪寒沐酒店', '礁溪寒沐酒店', '礁溪寒沐酒店', 'hotel', NULL, 'offline', 'TW', 1),
  ('m_聯合航空', '聯合航空', '聯合航空', 'travel', NULL, 'offline', 'TW', 1),
  ('m_豐生茶館梅川東店', '豐生茶館梅川東店', '豐生茶館梅川東店', 'dining', NULL, 'offline', 'TW', 1),
  ('m_雞湯大叔', '雞湯大叔', '雞湯大叔', 'dining', NULL, 'offline', 'TW', 1),
  ('m_鯡魚工作室', '鯡魚工作室', '鯡魚工作室', 'dining', NULL, 'offline', 'TW', 1),
  ('m_麗兒采家', '麗兒采家', '麗兒采家', 'retail', NULL, 'offline', 'TW', 1),
  ('m_麗寶福容大飯店', '麗寶福容大飯店', '麗寶福容大飯店', 'hotel', NULL, 'offline', 'TW', 1),
  ('m_麗寶樂園', '麗寶樂園', '麗寶樂園', 'theme_park', NULL, 'offline', 'TW', 1),
  ('m_寶齡婦幼館', '寶齡婦幼館', '寶齡婦幼館', 'retail', NULL, 'offline', 'TW', 1),
  ('m_朧板前燒肉', '朧板前燒肉', '朧板前燒肉', 'dining', NULL, 'offline', 'TW', 1),
  ('m_麵屋武藏', '麵屋武藏', '麵屋武藏', 'dining', NULL, 'offline', 'TW', 1),
  ('m_蘭城晶英酒店', '蘭城晶英酒店', '蘭城晶英酒店', 'hotel', NULL, 'offline', 'TW', 1),
  ('m_agoda', 'Agoda', 'Agoda', 'travel', NULL, 'offline', 'TW', 1),
  ('m_airbnb', 'Airbnb', 'Airbnb', 'travel', NULL, 'offline', 'TW', 1),
  ('m_ana全日空', 'ANA全日空', 'ANA全日空', 'travel', NULL, 'offline', 'TW', 1),
  ('m_another_eatery', 'Another Eatery', 'Another Eatery', 'dining', NULL, 'offline', 'TW', 1),
  ('m_apple_媒體服務', 'Apple 媒體服務', 'Apple 媒體服務', 'digital', NULL, 'offline', 'TW', 1),
  ('m_apple直營店', 'Apple直營店', 'Apple直營店', 'retail', NULL, 'offline', 'TW', 1),
  ('m_ashin_阿鑫', 'Ashin 阿鑫', 'Ashin 阿鑫', 'dining', NULL, 'offline', 'TW', 1),
  ('m_att_4_fun', 'ATT 4 FUN', 'ATT 4 FUN', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_aufglet', 'AUFGLET', 'AUFGLET', 'dining', NULL, 'offline', 'TW', 1),
  ('m_bellavita', 'BELLAVITA', 'BELLAVITA', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_bellini_caff', 'BELLINI CAFFÈ', 'BELLINI CAFFÈ', 'dining', NULL, 'offline', 'TW', 1),
  ('m_bellini_pasta_pasta', 'BELLINI Pasta Pasta', 'BELLINI Pasta Pasta', 'dining', NULL, 'offline', 'TW', 1),
  ('m_bic_camera', 'BIC CAMERA', 'BIC CAMERA', 'retail', NULL, 'offline', 'JP', 1),
  ('m_big_city遠東巨城購物中心', 'Big City遠東巨城購物中心', 'Big City遠東巨城購物中心', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_booking_com', 'Booking.com', 'Booking.com', 'travel', NULL, 'offline', 'TW', 1),
  ('m_canva', 'Canva', 'Canva', 'digital', NULL, 'offline', 'TW', 1),
  ('m_chatgpt', 'ChatGPT', 'ChatGPT', 'digital', NULL, 'offline', 'TW', 1),
  ('m_citylink', 'CITYLINK', 'CITYLINK', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_claude', 'Claude', 'Claude', 'digital', NULL, 'offline', 'TW', 1),
  ('m_coupang_酷澎_台灣', 'Coupang 酷澎(台灣)', 'Coupang 酷澎(台灣)', 'digital', NULL, 'offline', 'TW', 1),
  ('m_coupang酷澎', 'Coupang酷澎', 'Coupang酷澎', 'digital', NULL, 'offline', 'TW', 1),
  ('m_creammm_t', 'creammm.t', 'creammm.t', 'dining', NULL, 'offline', 'TW', 1),
  ('m_cursor', 'Cursor', 'Cursor', 'digital', NULL, 'offline', 'TW', 1),
  ('m_daiso大創百貨', 'DAISO大創百貨', 'DAISO大創百貨', 'retail', NULL, 'offline', 'TW', 1),
  ('m_disney', 'Disney+', 'Disney+', 'digital', NULL, 'offline', 'TW', 1),
  ('m_duolingo', 'Duolingo', 'Duolingo', 'digital', NULL, 'offline', 'TW', 1),
  ('m_etalking_kids', 'Etalking Kids', 'Etalking Kids', 'education', NULL, 'offline', 'TW', 1),
  ('m_evalue', 'EVALUE', 'EVALUE', 'ev_charging', NULL, 'offline', 'TW', 1),
  ('m_evoasis', 'EVOASIS', 'EVOASIS', 'ev_charging', NULL, 'offline', 'TW', 1),
  ('m_expedia', 'Expedia', 'Expedia', 'digital', NULL, 'offline', 'TW', 1),
  ('m_ezfly易飛網', 'Ezfly易飛網', 'Ezfly易飛網', 'travel', NULL, 'offline', 'TW', 1),
  ('m_eztravel易遊網', 'ezTravel易遊網', 'ezTravel易遊網', 'travel', NULL, 'offline', 'TW', 1),
  ('m_fake_sober', 'Fake Sober', 'Fake Sober', 'dining', NULL, 'offline', 'TW', 1),
  ('m_familymart', 'FamilyMart', 'FamilyMart', 'convenience_store', NULL, 'offline', 'JP', 1),
  ('m_foodpanda', 'foodpanda', 'foodpanda', 'dining', NULL, 'offline', 'TW', 1),
  ('m_funnow', 'FunNow', 'FunNow', 'dining', NULL, 'offline', 'TW', 1),
  ('m_gamma', 'Gamma', 'Gamma', 'digital', NULL, 'offline', 'TW', 1),
  ('m_gemini', 'Gemini', 'Gemini', 'digital', NULL, 'offline', 'TW', 1),
  ('m_global_mall環球購物中心', 'Global Mall環球購物中心', 'Global Mall環球購物中心', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_global_work', 'GLOBAL WORK', 'GLOBAL WORK', 'retail', NULL, 'offline', 'TW', 1),
  ('m_google_play', 'Google Play', 'Google Play', 'digital', NULL, 'offline', 'TW', 1),
  ('m_grab', 'Grab', 'Grab', 'travel', NULL, 'offline', 'TW', 1),
  ('m_gu', 'GU', 'GU', 'retail', NULL, 'offline', 'TW', 1),
  ('m_hare', 'HARE', 'HARE', 'retail', NULL, 'offline', 'TW', 1),
  ('m_heather', 'Heather', 'Heather', 'retail', NULL, 'offline', 'TW', 1),
  ('m_hoi好好生活', 'hoi好好生活', 'hoi好好生活', 'retail', NULL, 'offline', 'TW', 1),
  ('m_hola', 'HOLA', 'HOLA', 'retail', NULL, 'offline', 'TW', 1),
  ('m_hotels_com', 'Hotels.com', 'Hotels.com', 'digital', NULL, 'offline', 'TW', 1),
  ('m_icharging', 'iCharging', 'iCharging', 'ev_charging', NULL, 'offline', 'TW', 1),
  ('m_icoca', 'ICOCA', 'ICOCA', 'travel', NULL, 'offline', 'JP', 1),
  ('m_ikea宜家家居', 'IKEA宜家家居', 'IKEA宜家家居', 'retail', NULL, 'offline', 'TW', 1),
  ('m_irent', 'iRent', 'iRent', 'travel', NULL, 'offline', 'TW', 1),
  ('m_iski滑雪俱樂部', 'iSKI滑雪俱樂部', 'iSKI滑雪俱樂部', 'education', NULL, 'offline', 'TW', 1),
  ('m_jai_宅', 'JAI 宅', 'JAI 宅', 'dining', NULL, 'offline', 'TW', 1),
  ('m_jeanasis', 'JEANASIS', 'JEANASIS', 'retail', NULL, 'offline', 'TW', 1),
  ('m_kkday', 'KKday', 'KKday', 'travel', NULL, 'offline', 'TW', 1),
  ('m_klook', 'Klook', 'Klook', 'travel', NULL, 'offline', 'TW', 1),
  ('m_komboi', 'KOMBOI', 'KOMBOI', 'dining', NULL, 'offline', 'TW', 1),
  ('m_lakole', 'LAKOLE', 'LAKOLE', 'retail', NULL, 'offline', 'TW', 1),
  ('m_lalaport', 'LaLaport', 'LaLaport', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_lawson', 'LAWSON', 'LAWSON', 'convenience_store', NULL, 'offline', 'JP', 1),
  ('m_lepsim', 'LEPSIM', 'LEPSIM', 'retail', NULL, 'offline', 'TW', 1),
  ('m_little_wonders台灣官網', 'Little Wonders台灣官網', 'Little Wonders台灣官網', 'retail', NULL, 'offline', 'TW', 1),
  ('m_lopia台灣', 'LOPIA台灣', 'LOPIA台灣', 'supermarket', NULL, 'offline', 'TW', 1),
  ('m_lowrys_farm', 'LOWRYS FARM', 'LOWRYS FARM', 'retail', NULL, 'offline', 'TW', 1),
  ('m_mamas_papas台灣官網', 'Mamas&Papas台灣官網', 'Mamas&Papas台灣官網', 'retail', NULL, 'offline', 'TW', 1),
  ('m_max', 'Max', 'Max', 'digital', NULL, 'offline', 'TW', 1),
  ('m_mitsui_outlet_park', 'MITSUI OUTLET PARK', 'MITSUI OUTLET PARK', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_mitsui_shopping_park_lalaport', 'Mitsui Shopping Park LaLaport', 'Mitsui Shopping Park LaLaport', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_mo_mo_paradise', 'Mo-Mo-Paradise', 'Mo-Mo-Paradise', 'dining', NULL, 'offline', 'TW', 1),
  ('m_molino_手工義大利麵', 'MOLINO 手工義大利麵', 'MOLINO 手工義大利麵', 'dining', NULL, 'offline', 'TW', 1),
  ('m_momo購物網', 'momo購物網', 'momo購物網', 'digital', NULL, 'offline', 'TW', 1),
  ('m_money_jump_媽妳講親子餐廳', 'Money Jump 媽妳講親子餐廳', 'Money Jump 媽妳講親子餐廳', 'dining', NULL, 'offline', 'TW', 1),
  ('m_net', 'NET', 'NET', 'retail', NULL, 'offline', 'TW', 1),
  ('m_netflix', 'Netflix', 'Netflix', 'digital', NULL, 'offline', 'TW', 1),
  ('m_niko_and', 'niko and …', 'niko and …', 'retail', NULL, 'offline', 'TW', 1),
  ('m_nintendo', 'Nintendo', 'Nintendo', 'dining', NULL, 'offline', 'TW', 1),
  ('m_noke忠泰樂生活', 'NOKE忠泰樂生活', 'NOKE忠泰樂生活', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_notion', 'Notion', 'Notion', 'digital', NULL, 'offline', 'TW', 1),
  ('m_pageboy', 'PAGEBOY', 'PAGEBOY', 'retail', NULL, 'offline', 'TW', 1),
  ('m_pasmo', 'PASMO', 'PASMO', 'travel', NULL, 'offline', 'JP', 1),
  ('m_pastaio', 'Pastaio', 'Pastaio', 'dining', NULL, 'offline', 'TW', 1),
  ('m_pastaio_noodle_cafe', 'Pastaio noodle cafe', 'Pastaio noodle cafe', 'dining', NULL, 'offline', 'TW', 1),
  ('m_pchome_24h購物', 'PChome 24h購物', 'PChome 24h購物', 'digital', NULL, 'offline', 'TW', 1),
  ('m_perplexity', 'Perplexity', 'Perplexity', 'digital', NULL, 'offline', 'TW', 1),
  ('m_playstation', 'PlayStation', 'PlayStation', 'dining', NULL, 'offline', 'TW', 1),
  ('m_rageblue', 'RAGEBLUE', 'RAGEBLUE', 'retail', NULL, 'offline', 'TW', 1),
  ('m_repipi_armario', 'repipi armario', 'repipi armario', 'retail', NULL, 'offline', 'TW', 1),
  ('m_seahorse_originals台灣官網', 'Seahorse Originals台灣官網', 'Seahorse Originals台灣官網', 'retail', NULL, 'offline', 'TW', 1),
  ('m_skm_park', 'SKM Park', 'SKM Park', 'department_store', NULL, 'offline', 'TW', 1),
  ('m_sober_burger', 'Sober & Burger', 'Sober & Burger', 'dining', NULL, 'offline', 'TW', 1),
  ('m_sober_bakery', 'Sober Bakery', 'Sober Bakery', 'dining', NULL, 'offline', 'TW', 1),
  ('m_sozai', 'Sozai', 'Sozai', 'dining', NULL, 'offline', 'TW', 1),
  ('m_speak', 'Speak', 'Speak', 'digital', NULL, 'offline', 'TW', 1),
  ('m_spotify', 'Spotify', 'Spotify', 'digital', NULL, 'offline', 'TW', 1),
  ('m_standard_products', 'Standard Products', 'Standard Products', 'retail', NULL, 'offline', 'TW', 1),
  ('m_studio_clip', 'studio CLIP', 'studio CLIP', 'retail', NULL, 'offline', 'TW', 1),
  ('m_suica', 'SUICA', 'SUICA', 'travel', NULL, 'offline', 'JP', 1),
  ('m_tail', 'TAIL', 'TAIL', 'ev_charging', NULL, 'offline', 'TW', 1),
  ('m_taobaby濤寶日記', 'Taobaby濤寶日記', 'Taobaby濤寶日記', 'retail', NULL, 'offline', 'TW', 1),
  ('m_the_other_eatery中山小酒館', 'The other Eatery中山小酒館', 'The other Eatery中山小酒館', 'dining', NULL, 'offline', 'TW', 1),
  ('m_threeppy', 'THREEPPY', 'THREEPPY', 'retail', NULL, 'offline', 'TW', 1),
  ('m_trip_com', 'Trip.com', 'Trip.com', 'travel', NULL, 'offline', 'TW', 1),
  ('m_tsutaya_bookstore', 'TSUTAYA BOOKSTORE', 'TSUTAYA BOOKSTORE', 'retail', NULL, 'offline', 'TW', 1),
  ('m_tutorabc_junior', 'TutorABC Junior', 'TutorABC Junior', 'education', NULL, 'offline', 'TW', 1),
  ('m_u_power', 'U-POWER', 'U-POWER', 'ev_charging', NULL, 'offline', 'TW', 1),
  ('m_uber', 'Uber', 'Uber', 'travel', NULL, 'offline', 'TW', 1),
  ('m_uber_eats', 'Uber Eats', 'Uber Eats', 'dining', NULL, 'offline', 'TW', 1),
  ('m_uncle_ray串燒_牛飲_咖喱', 'UNCLE RAY串燒·牛飲·咖喱', 'UNCLE RAY串燒·牛飲·咖喱', 'dining', NULL, 'offline', 'TW', 1),
  ('m_uncle_shawn_燒肉餐酒館', 'UNCLE SHAWN 燒肉餐酒館', 'UNCLE SHAWN 燒肉餐酒館', 'dining', NULL, 'offline', 'TW', 1),
  ('m_uniqlo', 'UNIQLO', 'UNIQLO', 'retail', NULL, 'offline', 'TW', 1),
  ('m_utaggo', 'uTagGo', 'uTagGo', 'mobility', NULL, 'offline', 'TW', 1),
  ('m_xpark', 'Xpark', 'Xpark', 'theme_park', NULL, 'offline', 'TW', 1),
  ('m_yamaha音樂教室', 'Yamaha音樂教室', 'Yamaha音樂教室', 'education', NULL, 'offline', 'TW', 1),
  ('m_yayoi_彌生軒', 'YAYOI 彌生軒', 'YAYOI 彌生軒', 'dining', NULL, 'offline', 'TW', 1),
  ('m_yodobashi', 'Yodobashi', 'Yodobashi', 'retail', NULL, 'offline', 'JP', 1),
  ('m_youtube_premium', 'YouTube Premium', 'YouTube Premium', 'digital', NULL, 'offline', 'TW', 1),
  ('m_yoxi', 'yoxi', 'yoxi', 'travel', NULL, 'offline', 'TW', 1),
  ('m_凪ramen_nagi', 'ラーメン凪Ramen Nagi', 'ラーメン凪Ramen Nagi', 'dining', NULL, 'offline', 'TW', 1),
  ('m_摩斯漢堡', '摩斯漢堡', '摩斯漢堡', 'dining', NULL, 'offline', 'TW', 1),
  ('m_肯德基', '肯德基', '肯德基', 'dining', NULL, 'offline', 'TW', 1),
  ('m_頂呱呱', '頂呱呱', '頂呱呱', 'dining', NULL, 'offline', 'TW', 1),
  ('m_漢堡王', '漢堡王', '漢堡王', 'dining', NULL, 'offline', 'TW', 1),
  ('m_美而美', '美而美', '美而美', 'dining', NULL, 'offline', 'TW', 1),
  ('m_弘爺漢堡', '弘爺漢堡', '弘爺漢堡', 'dining', NULL, 'offline', 'TW', 1),
  ('m_早安美芝城', '早安美芝城', '早安美芝城', 'dining', NULL, 'offline', 'TW', 1),
  ('m_麥味登', '麥味登', '麥味登', 'dining', NULL, 'offline', 'TW', 1),
  ('m_星巴克', '星巴克', '星巴克', 'dining', NULL, 'offline', 'TW', 1),
  ('m_85度c', '85度C', '85度C', 'dining', NULL, 'offline', 'TW', 1),
  ('m_cama_caf', 'cama café', 'cama café', 'dining', NULL, 'offline', 'TW', 1),
  ('m_丹堤咖啡', '丹堤咖啡', '丹堤咖啡', 'dining', NULL, 'offline', 'TW', 1),
  ('m_怡客咖啡', '怡客咖啡', '怡客咖啡', 'dining', NULL, 'offline', 'TW', 1),
  ('m_大苑子', '大苑子', '大苑子', 'dining', NULL, 'offline', 'TW', 1),
  ('m_迷客夏', '迷客夏', '迷客夏', 'dining', NULL, 'offline', 'TW', 1),
  ('m_萬波', '萬波', '萬波', 'dining', NULL, 'offline', 'TW', 1),
  ('m_老虎堂', '老虎堂', '老虎堂', 'dining', NULL, 'offline', 'TW', 1),
  ('m_清心福全', '清心福全', '清心福全', 'dining', NULL, 'offline', 'TW', 1),
  ('m_coco都可', 'CoCo都可', 'CoCo都可', 'dining', NULL, 'offline', 'TW', 1),
  ('m_一芳水果茶', '一芳水果茶', '一芳水果茶', 'dining', NULL, 'offline', 'TW', 1),
  ('m_珍煮丹', '珍煮丹', '珍煮丹', 'dining', NULL, 'offline', 'TW', 1),
  ('m_得正', '得正', '得正', 'dining', NULL, 'offline', 'TW', 1),
  ('m_天仁茗茶', '天仁茗茶', '天仁茗茶', 'dining', NULL, 'offline', 'TW', 1),
  ('m_春水堂', '春水堂', '春水堂', 'dining', NULL, 'offline', 'TW', 1),
  ('m_錢都涮涮鍋', '錢都涮涮鍋', '錢都涮涮鍋', 'dining', NULL, 'offline', 'TW', 1),
  ('m_石二鍋', '石二鍋', '石二鍋', 'dining', NULL, 'offline', 'TW', 1),
  ('m_築間幸福鍋物', '築間幸福鍋物', '築間幸福鍋物', 'dining', NULL, 'offline', 'TW', 1),
  ('m_鼎王麻辣鍋', '鼎王麻辣鍋', '鼎王麻辣鍋', 'dining', NULL, 'offline', 'TW', 1),
  ('m_馬辣頂級麻辣鴛鴦火鍋', '馬辣頂級麻辣鴛鴦火鍋', '馬辣頂級麻辣鴛鴦火鍋', 'dining', NULL, 'offline', 'TW', 1),
  ('m_鼎泰豐', '鼎泰豐', '鼎泰豐', 'dining', NULL, 'offline', 'TW', 1),
  ('m_三商巧福', '三商巧福', '三商巧福', 'dining', NULL, 'offline', 'TW', 1),
  ('m_度小月', '度小月', '度小月', 'dining', NULL, 'offline', 'TW', 1),
  ('m_貴族世家', '貴族世家', '貴族世家', 'dining', NULL, 'offline', 'TW', 1),
  ('m_壽司郎', '壽司郎', '壽司郎', 'dining', NULL, 'offline', 'TW', 1),
  ('m_食其家', '食其家', '食其家', 'dining', NULL, 'offline', 'TW', 1),
  ('m_吉野家', '吉野家', '吉野家', 'dining', NULL, 'offline', 'TW', 1),
  ('m_丸龜製麵', '丸龜製麵', '丸龜製麵', 'dining', NULL, 'offline', 'TW', 1),
  ('m_爭鮮', '爭鮮', '爭鮮', 'dining', NULL, 'offline', 'TW', 1),
  ('m_品田牧場', '品田牧場', '品田牧場', 'dining', NULL, 'offline', 'TW', 1),
  ('m_王品台塑牛排', '王品台塑牛排', '王品台塑牛排', 'dining', NULL, 'offline', 'TW', 1),
  ('m_西堤牛排', '西堤牛排', '西堤牛排', 'dining', NULL, 'offline', 'TW', 1),
  ('m_原燒', '原燒', '原燒', 'dining', NULL, 'offline', 'TW', 1),
  ('m_藝奇', '藝奇', '藝奇', 'dining', NULL, 'offline', 'TW', 1),
  ('m_舒果', '舒果', '舒果', 'dining', NULL, 'offline', 'TW', 1),
  ('m_就饗鐵板燒', '就饗鐵板燒', '就饗鐵板燒', 'dining', NULL, 'offline', 'TW', 1),
  ('m_金咕韓式原塊烤肉', '金咕韓式原塊烤肉', '金咕韓式原塊烤肉', 'dining', NULL, 'offline', 'TW', 1),
  ('m_瓦城', '瓦城', '瓦城', 'dining', NULL, 'offline', 'TW', 1),
  ('m_非常泰', '非常泰', '非常泰', 'dining', NULL, 'offline', 'TW', 1),
  ('m_大心', '大心', '大心', 'dining', NULL, 'offline', 'TW', 1),
  ('m_1010湘', '1010湘', '1010湘', 'dining', NULL, 'offline', 'TW', 1),
  ('m_十食湘', '十食湘', '十食湘', 'dining', NULL, 'offline', 'TW', 1),
  ('m_饗食天堂', '饗食天堂', '饗食天堂', 'dining', NULL, 'offline', 'TW', 1),
  ('m_漢來海港', '漢來海港', '漢來海港', 'dining', NULL, 'offline', 'TW', 1),
  ('m_涓豆腐', '涓豆腐', '涓豆腐', 'dining', NULL, 'offline', 'TW', 1),
  ('m_老四川', '老四川', '老四川', 'dining', NULL, 'offline', 'TW', 1),
  ('m_達美樂', '達美樂', '達美樂', 'dining', NULL, 'offline', 'TW', 1),
  ('m_必勝客', '必勝客', '必勝客', 'dining', NULL, 'offline', 'TW', 1),
  ('m_鬍鬚張魯肉飯', '鬍鬚張魯肉飯', '鬍鬚張魯肉飯', 'dining', NULL, 'offline', 'TW', 1),
  ('m_欣葉台菜', '欣葉台菜', '欣葉台菜', 'dining', NULL, 'offline', 'TW', 1),
  ('m_悟饕池上便當', '悟饕池上便當', '悟饕池上便當', 'dining', NULL, 'offline', 'TW', 1),
  ('m_我家牛排', '我家牛排', '我家牛排', 'dining', NULL, 'offline', 'TW', 1),
  ('m_添好運', '添好運', '添好運', 'dining', NULL, 'offline', 'TW', 1),
  ('m_樺達奶茶', '樺達奶茶', '樺達奶茶', 'dining', NULL, 'offline', 'TW', 1),
  ('m_ok超商', 'OK超商', 'OK超商', 'convenience_store', NULL, 'offline', 'TW', 1),
  ('m_美廉社', '美廉社', '美廉社', 'convenience_store', NULL, 'offline', 'TW', 1),
  ('m_寶雅', '寶雅', '寶雅', 'drugstore', NULL, 'offline', 'TW', 1),
  ('m_小三美日', '小三美日', '小三美日', 'drugstore', NULL, 'offline', 'TW', 1),
  ('m_元祖', '元祖', '元祖', 'retail', NULL, 'offline', 'TW', 1),
  ('m_亞尼克', '亞尼克', '亞尼克', 'retail', NULL, 'offline', 'TW', 1),
  ('m_晶英酒店', '晶英酒店', '晶英酒店', 'hotel', NULL, 'offline', 'TW', 1),
  ('m_老爺酒店', '老爺酒店', '老爺酒店', 'hotel', NULL, 'offline', 'TW', 1),
  ('m_君品酒店', '君品酒店', '君品酒店', 'hotel', NULL, 'offline', 'TW', 1),
  ('m_翰品酒店', '翰品酒店', '翰品酒店', 'hotel', NULL, 'offline', 'TW', 1),
  ('m_兆品酒店', '兆品酒店', '兆品酒店', 'hotel', NULL, 'offline', 'TW', 1),
  ('m_福容大飯店', '福容大飯店', '福容大飯店', 'hotel', NULL, 'offline', 'TW', 1),
  ('m_六福萬怡酒店', '六福萬怡酒店', '六福萬怡酒店', 'hotel', NULL, 'offline', 'TW', 1),
  ('m_藏壽司', '藏壽司', '藏壽司', 'dining', NULL, 'offline', 'TW', 1),
  ('m_路易莎咖啡', '路易莎咖啡', '路易莎咖啡', 'dining', NULL, 'offline', 'TW', 1),
  ('m_小北百貨', '小北百貨', '小北百貨', 'retail', NULL, 'offline', 'TW', 1);

INSERT INTO merchant_aliases (merchant_id, alias, normalized_alias) VALUES
  ('m_7_eleven_7_11_實體門市', '7-11', '7-11'),
  ('m_7_eleven_7_11_實體門市', '7-ELEVEN', '7-eleven'),
  ('m_7_eleven_7_11_實體門市', '小七', '小七'),
  ('m_7_eleven_7_11_實體門市', '統一超商', '統一超商'),
  ('m_7_eleven_7_11_實體門市', '7-ELEVEN 實體門市', '7-eleven實體門市'),
  ('m_一風堂', 'Ippudo', 'ippudo'),
  ('m_三友藥妝tomod_s', 'Tomod\'s', 'tomod\'s'),
  ('m_土耳其航空', 'Turkish Airlines', 'turkishairlines'),
  ('m_大阪環球影城', 'USJ', 'usj'),
  ('m_大阪環球影城', '環球影城', '環球影城'),
  ('m_大阪環球影城', '大阪環球影城(USJ)', '大阪環球影城(usj)'),
  ('m_大葉高島屋', 'Takashimaya', 'takashimaya'),
  ('m_大韓航空', 'Korean Air', 'koreanair'),
  ('m_中華航空', 'China Airlines', 'chinaairlines'),
  ('m_中華航空', '華航', '華航'),
  ('m_日本航空', 'JAL', 'jal'),
  ('m_日本航空', 'Japan Airlines', 'japanairlines'),
  ('m_卡達航空', 'Qatar Airways', 'qatarairways'),
  ('m_台灣虎航', 'Tigerair Taiwan', 'tigerairtaiwan'),
  ('m_台灣虎航', '虎航', '虎航'),
  ('m_全家便利商店_實體門市', '全家', '全家'),
  ('m_全聯福利中心', '全聯', '全聯'),
  ('m_全聯福利中心', 'PX Mart', 'pxmart'),
  ('m_亞洲航空', 'AirAsia', 'airasia'),
  ('m_屈臣氏', 'Watsons', 'watsons'),
  ('m_東京迪士尼', 'Tokyo Disneyland', 'tokyodisneyland'),
  ('m_東京迪士尼', '迪士尼', '迪士尼'),
  ('m_東京迪士尼', '東京迪士尼樂園', '東京迪士尼樂園'),
  ('m_東京華納兄弟哈利波特影城', '哈利波特影城', '哈利波特影城'),
  ('m_東京華納兄弟哈利波特影城', 'Harry Potter Studio Tour', 'harrypotterstudiotour'),
  ('m_東橫inn', 'Toyoko Inn', 'toyokoinn'),
  ('m_松本清', 'Matsumoto Kiyoshi', 'matsumotokiyoshi'),
  ('m_法國航空', 'Air France', 'airfrance'),
  ('m_長榮航空', 'EVA Air', 'evaair'),
  ('m_長榮航空', '長榮', '長榮'),
  ('m_阿聯酋航空', 'Emirates', 'emirates'),
  ('m_星宇航空', 'STARLUX', 'starlux'),
  ('m_星宇航空', '星宇', '星宇'),
  ('m_星野集團', 'Hoshino Resorts', 'hoshinoresorts'),
  ('m_國泰航空', 'Cathay Pacific', 'cathaypacific'),
  ('m_康是美', 'Cosmed', 'cosmed'),
  ('m_捷星航空', 'Jetstar', 'jetstar'),
  ('m_麥當勞', 'McDonald\'s', 'mcdonald\'s'),
  ('m_萊爾富實體門市', '萊爾富', '萊爾富'),
  ('m_萊爾富實體門市', 'Hi-Life', 'hi-life'),
  ('m_越捷航空', 'VietJet', 'vietjet'),
  ('m_微風廣場', '微風', '微風'),
  ('m_微風廣場', 'Breeze Center', 'breezecenter'),
  ('m_新加坡航空', 'Singapore Airlines', 'singaporeairlines'),
  ('m_新光三越', '新光', '新光'),
  ('m_新光三越', 'Shin Kong Mitsukoshi', 'shinkongmitsukoshi'),
  ('m_誠品生活', '誠品', '誠品'),
  ('m_誠品生活', 'Eslite', 'eslite'),
  ('m_達美航空', 'Delta', 'delta'),
  ('m_達美航空', 'Delta Air Lines', 'deltaairlines'),
  ('m_遠東百貨', '遠百', '遠百'),
  ('m_酷航', 'Scoot', 'scoot'),
  ('m_樂桃航空', 'Peach Aviation', 'peachaviation'),
  ('m_樂桃航空', '樂桃', '樂桃'),
  ('m_蝦皮購物', '蝦皮', '蝦皮'),
  ('m_蝦皮購物', 'Shopee', 'shopee'),
  ('m_環球購物中心', 'Global Mall', 'globalmall'),
  ('m_聯合航空', 'United Airlines', 'unitedairlines'),
  ('m_ana全日空', 'ANA', 'ana'),
  ('m_ana全日空', 'All Nippon Airways', 'allnipponairways'),
  ('m_big_city遠東巨城購物中心', '巨城', '巨城'),
  ('m_big_city遠東巨城購物中心', 'Big City', 'bigcity'),
  ('m_coupang_酷澎_台灣', 'Coupang', 'coupang'),
  ('m_coupang_酷澎_台灣', '酷澎', '酷澎'),
  ('m_daiso大創百貨', 'DAISO', 'daiso'),
  ('m_daiso大創百貨', '大創', '大創'),
  ('m_google_play', 'Play Store', 'playstore'),
  ('m_ikea宜家家居', 'IKEA', 'ikea'),
  ('m_ikea宜家家居', '宜家', '宜家'),
  ('m_momo購物網', 'momo', 'momo'),
  ('m_pchome_24h購物', 'PChome', 'pchome'),
  ('m_uniqlo', '優衣庫', '優衣庫'),
  ('m_yayoi_彌生軒', 'YAYOI彌生軒', 'yayoi彌生軒'),
  ('m_摩斯漢堡', 'MOS Burger', 'mosburger'),
  ('m_摩斯漢堡', 'MOS', 'mos'),
  ('m_肯德基', 'KFC', 'kfc'),
  ('m_漢堡王', 'Burger King', 'burgerking'),
  ('m_星巴克', 'Starbucks', 'starbucks'),
  ('m_cama_caf', 'cama', 'cama'),
  ('m_壽司郎', 'Sushiro', 'sushiro'),
  ('m_食其家', 'Sukiya', 'sukiya'),
  ('m_吉野家', 'Yoshinoya', 'yoshinoya'),
  ('m_丸龜製麵', 'Marugame Seimen', 'marugameseimen'),
  ('m_達美樂', 'Domino\'s', 'domino\'s'),
  ('m_達美樂', 'Domino\'s Pizza', 'domino\'spizza'),
  ('m_必勝客', 'Pizza Hut', 'pizzahut'),
  ('m_寶雅', 'POYA', 'poya'),
  ('m_晶英酒店', 'Silks Place', 'silksplace'),
  ('m_六福萬怡酒店', 'Marriott', 'marriott'),
  ('m_六福萬怡酒店', '萬怡', '萬怡'),
  ('m_藏壽司', 'Kura Sushi', 'kurasushi'),
  ('m_路易莎咖啡', '路易莎', '路易莎'),
  ('m_路易莎咖啡', 'Louisa Coffee', 'louisacoffee');

INSERT INTO merchant_tags (merchant_id, tag) VALUES
  ('m_10mois台灣官網', 'baby_kids'),
  ('m_55688', 'transport'),
  ('m_55688', 'taxi'),
  ('m_7_eleven', 'chain_store'),
  ('m_7_eleven', 'japan'),
  ('m_7_eleven_7_11_實體門市', 'chain_store'),
  ('m_一風堂', 'restaurant'),
  ('m_九族文化村', 'attraction'),
  ('m_二本松涮涮屋', 'restaurant'),
  ('m_三井outlet', 'mall'),
  ('m_三友藥妝tomod_s', 'health_beauty'),
  ('m_三友藥妝tomod_s', 'japanese_brand'),
  ('m_三賀旅行社', 'travel_agency'),
  ('m_三越', 'mall'),
  ('m_三越', 'japan'),
  ('m_三點三', 'restaurant'),
  ('m_久碳吉炭火燒肉', 'restaurant'),
  ('m_千葉火鍋', 'restaurant'),
  ('m_土耳其航空', 'airline'),
  ('m_大戶屋', 'restaurant'),
  ('m_大全聯', 'grocery'),
  ('m_大江國際購物中心', 'mall'),
  ('m_大阪環球影城', 'attraction'),
  ('m_大阪環球影城', 'japan'),
  ('m_大河屋_燒肉丼_串燒', 'restaurant'),
  ('m_大溪笠復威斯汀度假酒店', 'lodging'),
  ('m_大葉高島屋', 'mall'),
  ('m_大樹先生的家', 'baby_kids'),
  ('m_大韓航空', 'airline'),
  ('m_小方舟串燒酒場', 'restaurant'),
  ('m_小叮噹科學園區主題樂園', 'attraction'),
  ('m_小米台灣', 'electronics'),
  ('m_小島3_5度親子餐廳', 'baby_kids'),
  ('m_小樹購', 'ecommerce'),
  ('m_山富旅遊', 'travel_agency'),
  ('m_中友百貨', 'mall'),
  ('m_中華航空', 'airline'),
  ('m_五福旅遊', 'travel_agency'),
  ('m_六福村主題樂園', 'attraction'),
  ('m_六福莊', 'lodging'),
  ('m_六福莊', 'resort'),
  ('m_天吉屋', 'restaurant'),
  ('m_天貓', 'ecommerce'),
  ('m_太平洋百貨', 'mall'),
  ('m_屯京拉麵', 'restaurant'),
  ('m_巴哈姆特動畫瘋', 'restaurant'),
  ('m_日本航空', 'airline'),
  ('m_日本橋浜町食事处', 'restaurant'),
  ('m_日藥本舖', 'health_beauty'),
  ('m_日藥本舖', 'japanese_brand'),
  ('m_毛丼丼飯專門店', 'restaurant'),
  ('m_毛房蔥柚鍋_冷藏肉專門', 'restaurant'),
  ('m_毛蔬亞洲蔬食', 'restaurant'),
  ('m_水鳥和洋創作料理', 'restaurant'),
  ('m_火火燒肉販賣所', 'restaurant'),
  ('m_加利利旅行社', 'travel_agency'),
  ('m_卡多摩', 'baby_kids'),
  ('m_卡多摩嬰童館', 'baby_kids'),
  ('m_卡達航空', 'airline'),
  ('m_古北町台灣官網', 'baby_kids'),
  ('m_可樂旅遊', 'travel_agency'),
  ('m_台中漢神洲際購物廣場', 'mall'),
  ('m_台北101', 'mall'),
  ('m_台北市私立道明外僑學校', 'school'),
  ('m_台北私立立人國際國小', 'school'),
  ('m_台北美國學校', 'school'),
  ('m_台北喜來登大飯店', 'lodging'),
  ('m_台北歐洲學校', 'school'),
  ('m_台亞加油站', 'fuel'),
  ('m_台南晶英酒店', 'lodging'),
  ('m_台茂購物中心', 'mall'),
  ('m_台塑生醫實體門市', 'health_beauty'),
  ('m_台塑生醫實體門市', 'biotech'),
  ('m_台塑石油加油站', 'fuel'),
  ('m_台塑蔬菜實體門市', 'grocery'),
  ('m_台塑蔬菜實體門市', 'fresh_produce'),
  ('m_台塑購物網', 'ecommerce'),
  ('m_台鐵', 'transport'),
  ('m_台鐵', 'rail'),
  ('m_台灣大車隊', 'transport'),
  ('m_台灣中油', 'fuel'),
  ('m_台灣中油_直營站', 'fuel'),
  ('m_台灣虎航', 'airline'),
  ('m_台灣高鐵', 'transport'),
  ('m_台灣壽司郎', 'restaurant'),
  ('m_巧虎夢想樂園', 'attraction'),
  ('m_札幌藥妝', 'health_beauty'),
  ('m_札幌藥妝', 'japanese_brand'),
  ('m_永利旅行社', 'travel_agency'),
  ('m_永旺', 'mall'),
  ('m_永旺', 'japan'),
  ('m_立秋_li_chiu', 'restaurant'),
  ('m_全家便利商店_實體門市', 'chain_store'),
  ('m_全國電子', 'electronics'),
  ('m_全球迪士尼飯店', 'lodging'),
  ('m_全聯福利中心', 'grocery'),
  ('m_全聯福利中心_實體門市', 'grocery'),
  ('m_吉天麩羅', 'restaurant'),
  ('m_吉豚屋', 'restaurant'),
  ('m_好樂迪ktv', 'ktv'),
  ('m_好嶼_hosu', 'restaurant'),
  ('m_安琪兒婦嬰百貨', 'baby_kids'),
  ('m_有你真好湘菜沙龍', 'restaurant'),
  ('m_朱宗慶打擊樂教學系統', 'school'),
  ('m_汐游寶寶', 'school'),
  ('m_肉料理福', 'restaurant'),
  ('m_你家樓下', 'restaurant'),
  ('m_宏匯廣場', 'mall'),
  ('m_找到了旅行社', 'travel_agency'),
  ('m_杏一藥局', 'health_beauty'),
  ('m_秀泰生活', 'mall'),
  ('m_車麻吉', 'parking'),
  ('m_亞洲航空', 'airline'),
  ('m_享千葉火鍋', 'restaurant'),
  ('m_享溫馨ktv', 'ktv'),
  ('m_京丘炭火燒鳥專門店', 'restaurant'),
  ('m_京丘燒鳥酒処', 'restaurant'),
  ('m_京站', 'mall'),
  ('m_和逸飯店', 'lodging'),
  ('m_和運租車', 'transport'),
  ('m_定食8', 'restaurant'),
  ('m_宜兒樂', 'baby_kids'),
  ('m_宜蘭礁溪鳳凰酒店', 'lodging'),
  ('m_屈臣氏', 'health_beauty'),
  ('m_所_suo', 'restaurant'),
  ('m_拓元售票', 'ticketing'),
  ('m_昇恆昌', 'mall'),
  ('m_東京迪士尼', 'attraction'),
  ('m_東京迪士尼', 'japan'),
  ('m_東京華納兄弟哈利波特影城', 'attraction'),
  ('m_東南旅遊', 'travel_agency'),
  ('m_東橫inn', 'lodging'),
  ('m_松本清', 'health_beauty'),
  ('m_松本清', 'japanese_brand'),
  ('m_欣葉日本料理', 'restaurant'),
  ('m_欣葉日本料理_彩膳楽亭', 'restaurant'),
  ('m_法國的秘密甜點', 'restaurant'),
  ('m_法國航空', 'airline'),
  ('m_芮秋_rachel', 'restaurant'),
  ('m_花蓮遠雄悅來大飯店', 'lodging'),
  ('m_金子半之助', 'restaurant'),
  ('m_長汎假期', 'travel_agency'),
  ('m_長庚生技實體門市', 'health_beauty'),
  ('m_長庚生技實體門市', 'biotech'),
  ('m_長榮航空', 'airline'),
  ('m_阿聯酋航空', 'airline'),
  ('m_青沐', 'restaurant'),
  ('m_俏媽咪', 'baby_kids'),
  ('m_南紡購物中心', 'mall'),
  ('m_威秀影城', 'cinema'),
  ('m_思夢樂', 'apparel'),
  ('m_思夢樂', 'japanese_brand'),
  ('m_星宇航空', 'airline'),
  ('m_星野集團', 'lodging'),
  ('m_星聚點ktv', 'ktv'),
  ('m_春囍打邊爐', 'restaurant'),
  ('m_祇園_禪院壽喜燒', 'restaurant'),
  ('m_美麗華', 'mall'),
  ('m_耐斯廣場', 'mall'),
  ('m_唐吉訶德', 'discount_store'),
  ('m_唐吉訶德', 'japan'),
  ('m_家樂福', 'grocery'),
  ('m_家樂福', 'hypermarket'),
  ('m_格上租車', 'transport'),
  ('m_桃園名人堂花園大飯店', 'lodging'),
  ('m_特力屋', 'home_goods'),
  ('m_特斯拉', 'automobile'),
  ('m_特斯拉', 'ev'),
  ('m_馬禮遜學校', 'school'),
  ('m_高島屋', 'mall'),
  ('m_高島屋', 'japan'),
  ('m_高雄美國學校', 'school'),
  ('m_高雄萬豪酒店', 'lodging'),
  ('m_高鐵', 'transport'),
  ('m_高鐵', 'rail'),
  ('m_做茶菜', 'restaurant'),
  ('m_國內餐飲', 'mall'),
  ('m_國泰航空', 'airline'),
  ('m_國賓影城', 'cinema'),
  ('m_康乃薾美國學校', 'school'),
  ('m_康是美', 'health_beauty'),
  ('m_康橋國際學校', 'school'),
  ('m_捷星航空', 'airline'),
  ('m_涮乃葉', 'restaurant'),
  ('m_涮之華', 'restaurant'),
  ('m_淘寶', 'ecommerce'),
  ('m_淘寶網', 'mall'),
  ('m_理想旅遊', 'travel_agency'),
  ('m_陳阿姨火鍋灶咖', 'restaurant'),
  ('m_陶板屋', 'restaurant'),
  ('m_髙_gao_taipei', 'restaurant'),
  ('m_鳥苑_torien_yakitori', 'restaurant'),
  ('m_麥當勞', 'restaurant'),
  ('m_麥當勞', 'fast_food'),
  ('m_勝博殿', 'restaurant'),
  ('m_喜鴻假期', 'travel_agency'),
  ('m_嵐山熟成牛_專売', 'restaurant'),
  ('m_復興實驗高中', 'school'),
  ('m_竣師父牛肉麵', 'restaurant'),
  ('m_粥起粥底火鍋熱炒', 'restaurant'),
  ('m_統一時代台北店', 'mall'),
  ('m_統一時代百貨', 'mall'),
  ('m_統一速邁樂加油站', 'fuel'),
  ('m_華泰名品城', 'mall'),
  ('m_華盛頓小學', 'school'),
  ('m_萊爾富實體門市', 'chain_store'),
  ('m_越捷航空', 'airline'),
  ('m_雄獅旅遊', 'travel_agency'),
  ('m_雲門舞集舞蹈教室', 'school'),
  ('m_雲品溫泉酒店', 'lodging'),
  ('m_媽咪愛', 'baby_kids'),
  ('m_媽媽好', 'baby_kids'),
  ('m_嵩_sung', 'restaurant'),
  ('m_微風百貨', 'mall'),
  ('m_微風廣場', 'mall'),
  ('m_新千葉火鍋', 'restaurant'),
  ('m_新月廣場', 'mall'),
  ('m_新加坡航空', 'airline'),
  ('m_新光三越', 'restaurant'),
  ('m_新光三越百貨', 'mall'),
  ('m_新光影城', 'cinema'),
  ('m_新宿內臟燒肉', 'restaurant'),
  ('m_極千葉火鍋', 'restaurant'),
  ('m_煙波大飯店新竹湖濱館', 'lodging'),
  ('m_瑞穗天合國際觀光酒店', 'lodging'),
  ('m_萬家福_樂家康', 'mall'),
  ('m_義大皇家酒店', 'lodging'),
  ('m_義大遊樂世界', 'attraction'),
  ('m_蜀叔麻辣鍋', 'restaurant'),
  ('m_誠品生活', 'bookstore'),
  ('m_誠品生活', 'department_store'),
  ('m_達美航空', 'airline'),
  ('m_壽司美登利', 'restaurant'),
  ('m_壽司涮乃葉', 'restaurant'),
  ('m_夢時代', 'mall'),
  ('m_漢神巨蛋', 'mall'),
  ('m_漢神百貨', 'mall'),
  ('m_福懋加油站', 'fuel'),
  ('m_維多利亞雙語中小學', 'school'),
  ('m_遠東百貨', 'mall'),
  ('m_遠東garden_city', 'mall'),
  ('m_遠東sogo', 'mall'),
  ('m_遠東sogo百貨', 'mall'),
  ('m_酷航', 'airline'),
  ('m_銀杏中餐廳', 'restaurant'),
  ('m_鳳凰旅行社', 'travel_agency'),
  ('m_鳳凰旅遊', 'travel_agency'),
  ('m_劍湖山世界主題樂園', 'attraction'),
  ('m_廣三sogo', 'mall'),
  ('m_樂兒屋', 'baby_kids'),
  ('m_樂桃航空', 'airline'),
  ('m_樂麵屋', 'restaurant'),
  ('m_澄居烤物燒肉', 'restaurant'),
  ('m_稻鎮經典台灣菜', 'restaurant'),
  ('m_蝦皮購物', 'ecommerce'),
  ('m_輝室', 'restaurant'),
  ('m_墾丁凱撒大飯店', 'lodging'),
  ('m_橋山壽喜燒', 'restaurant'),
  ('m_燒肉smile', 'restaurant'),
  ('m_燒鳩', 'restaurant'),
  ('m_錢櫃ktv', 'ktv'),
  ('m_澀_sur', 'restaurant'),
  ('m_燦坤', 'electronics'),
  ('m_燦星旅遊', 'travel_agency'),
  ('m_環球購物中心', 'mall'),
  ('m_礁溪寒沐酒店', 'lodging'),
  ('m_聯合航空', 'airline'),
  ('m_豐生茶館梅川東店', 'restaurant'),
  ('m_雞湯大叔', 'restaurant'),
  ('m_鯡魚工作室', 'restaurant'),
  ('m_麗兒采家', 'baby_kids'),
  ('m_麗寶福容大飯店', 'lodging'),
  ('m_麗寶樂園', 'attraction'),
  ('m_寶齡婦幼館', 'baby_kids'),
  ('m_朧板前燒肉', 'restaurant'),
  ('m_麵屋武藏', 'restaurant'),
  ('m_蘭城晶英酒店', 'lodging'),
  ('m_agoda', 'ota'),
  ('m_agoda', 'hotel_booking'),
  ('m_airbnb', 'ota'),
  ('m_airbnb', 'hotel_booking'),
  ('m_ana全日空', 'airline'),
  ('m_another_eatery', 'restaurant'),
  ('m_apple_媒體服務', 'streaming'),
  ('m_apple_媒體服務', 'subscription'),
  ('m_apple直營店', 'electronics'),
  ('m_ashin_阿鑫', 'restaurant'),
  ('m_att_4_fun', 'mall'),
  ('m_aufglet', 'restaurant'),
  ('m_bellavita', 'mall'),
  ('m_bellini_caff', 'restaurant'),
  ('m_bellini_pasta_pasta', 'restaurant'),
  ('m_bic_camera', 'electronics'),
  ('m_bic_camera', 'japan'),
  ('m_big_city遠東巨城購物中心', 'mall'),
  ('m_booking_com', 'ota'),
  ('m_booking_com', 'hotel_booking'),
  ('m_canva', 'ai_tool'),
  ('m_canva', 'productivity'),
  ('m_chatgpt', 'ai_tool'),
  ('m_chatgpt', 'productivity'),
  ('m_citylink', 'mall'),
  ('m_claude', 'ai_tool'),
  ('m_claude', 'productivity'),
  ('m_coupang_酷澎_台灣', 'ecommerce'),
  ('m_coupang酷澎', 'ecommerce'),
  ('m_coupang酷澎', 'ota'),
  ('m_creammm_t', 'restaurant'),
  ('m_cursor', 'ai_tool'),
  ('m_cursor', 'productivity'),
  ('m_daiso大創百貨', 'variety_store'),
  ('m_daiso大創百貨', 'japanese_brand'),
  ('m_disney', 'streaming'),
  ('m_disney', 'subscription'),
  ('m_duolingo', 'ai_tool'),
  ('m_duolingo', 'productivity'),
  ('m_etalking_kids', 'school'),
  ('m_expedia', 'ecommerce'),
  ('m_expedia', 'ota'),
  ('m_ezfly易飛網', 'travel_agency'),
  ('m_eztravel易遊網', 'ota'),
  ('m_eztravel易遊網', 'hotel_booking'),
  ('m_fake_sober', 'restaurant'),
  ('m_familymart', 'chain_store'),
  ('m_familymart', 'japan'),
  ('m_foodpanda', 'restaurant'),
  ('m_foodpanda', 'delivery'),
  ('m_foodpanda', 'app'),
  ('m_funnow', 'restaurant'),
  ('m_gamma', 'ai_tool'),
  ('m_gamma', 'productivity'),
  ('m_gemini', 'ai_tool'),
  ('m_gemini', 'productivity'),
  ('m_global_mall環球購物中心', 'mall'),
  ('m_global_work', 'apparel'),
  ('m_global_work', 'japanese_brand'),
  ('m_google_play', 'streaming'),
  ('m_google_play', 'subscription'),
  ('m_grab', 'transport'),
  ('m_gu', 'apparel'),
  ('m_gu', 'japanese_brand'),
  ('m_hare', 'apparel'),
  ('m_hare', 'japanese_brand'),
  ('m_heather', 'apparel'),
  ('m_heather', 'japanese_brand'),
  ('m_hoi好好生活', 'home_goods'),
  ('m_hola', 'home_goods'),
  ('m_hotels_com', 'ecommerce'),
  ('m_hotels_com', 'ota'),
  ('m_icoca', 'transport'),
  ('m_icoca', 'ic_card'),
  ('m_icoca', 'japan'),
  ('m_ikea宜家家居', 'home_goods'),
  ('m_irent', 'transport'),
  ('m_iski滑雪俱樂部', 'school'),
  ('m_jai_宅', 'restaurant'),
  ('m_jeanasis', 'apparel'),
  ('m_jeanasis', 'japanese_brand'),
  ('m_kkday', 'ota'),
  ('m_kkday', 'hotel_booking'),
  ('m_klook', 'ota'),
  ('m_klook', 'hotel_booking'),
  ('m_komboi', 'restaurant'),
  ('m_lakole', 'apparel'),
  ('m_lakole', 'japanese_brand'),
  ('m_lalaport', 'mall'),
  ('m_lawson', 'chain_store'),
  ('m_lawson', 'japan'),
  ('m_lepsim', 'apparel'),
  ('m_lepsim', 'japanese_brand'),
  ('m_little_wonders台灣官網', 'baby_kids'),
  ('m_lopia台灣', 'grocery'),
  ('m_lowrys_farm', 'apparel'),
  ('m_lowrys_farm', 'japanese_brand'),
  ('m_mamas_papas台灣官網', 'baby_kids'),
  ('m_max', 'streaming'),
  ('m_max', 'subscription'),
  ('m_mitsui_outlet_park', 'mall'),
  ('m_mitsui_shopping_park_lalaport', 'mall'),
  ('m_mo_mo_paradise', 'restaurant'),
  ('m_molino_手工義大利麵', 'restaurant'),
  ('m_momo購物網', 'ecommerce'),
  ('m_money_jump_媽妳講親子餐廳', 'restaurant'),
  ('m_net', 'apparel'),
  ('m_netflix', 'streaming'),
  ('m_netflix', 'subscription'),
  ('m_niko_and', 'apparel'),
  ('m_niko_and', 'japanese_brand'),
  ('m_nintendo', 'restaurant'),
  ('m_noke忠泰樂生活', 'mall'),
  ('m_notion', 'ai_tool'),
  ('m_notion', 'productivity'),
  ('m_pageboy', 'apparel'),
  ('m_pageboy', 'japanese_brand'),
  ('m_pasmo', 'transport'),
  ('m_pasmo', 'ic_card'),
  ('m_pasmo', 'japan'),
  ('m_pastaio', 'restaurant'),
  ('m_pastaio_noodle_cafe', 'restaurant'),
  ('m_pchome_24h購物', 'ecommerce'),
  ('m_perplexity', 'ai_tool'),
  ('m_perplexity', 'productivity'),
  ('m_playstation', 'restaurant'),
  ('m_rageblue', 'apparel'),
  ('m_rageblue', 'japanese_brand'),
  ('m_repipi_armario', 'apparel'),
  ('m_repipi_armario', 'japanese_brand'),
  ('m_seahorse_originals台灣官網', 'baby_kids'),
  ('m_skm_park', 'mall'),
  ('m_sober_burger', 'restaurant'),
  ('m_sober_bakery', 'restaurant'),
  ('m_sozai', 'restaurant'),
  ('m_speak', 'ai_tool'),
  ('m_speak', 'productivity'),
  ('m_spotify', 'streaming'),
  ('m_spotify', 'subscription'),
  ('m_standard_products', 'variety_store'),
  ('m_standard_products', 'japanese_brand'),
  ('m_studio_clip', 'apparel'),
  ('m_studio_clip', 'japanese_brand'),
  ('m_suica', 'transport'),
  ('m_suica', 'ic_card'),
  ('m_suica', 'japan'),
  ('m_taobaby濤寶日記', 'baby_kids'),
  ('m_the_other_eatery中山小酒館', 'restaurant'),
  ('m_threeppy', 'variety_store'),
  ('m_threeppy', 'japanese_brand'),
  ('m_trip_com', 'ota'),
  ('m_trip_com', 'hotel_booking'),
  ('m_tsutaya_bookstore', 'bookstore'),
  ('m_tsutaya_bookstore', 'japanese_brand'),
  ('m_tutorabc_junior', 'school'),
  ('m_uber', 'transport'),
  ('m_uber_eats', 'restaurant'),
  ('m_uber_eats', 'delivery'),
  ('m_uber_eats', 'app'),
  ('m_uncle_ray串燒_牛飲_咖喱', 'restaurant'),
  ('m_uncle_shawn_燒肉餐酒館', 'restaurant'),
  ('m_uniqlo', 'apparel'),
  ('m_uniqlo', 'japanese_brand'),
  ('m_utaggo', 'parking'),
  ('m_xpark', 'attraction'),
  ('m_xpark', 'aquarium'),
  ('m_yamaha音樂教室', 'school'),
  ('m_yayoi_彌生軒', 'restaurant'),
  ('m_yodobashi', 'electronics'),
  ('m_yodobashi', 'japan'),
  ('m_youtube_premium', 'streaming'),
  ('m_youtube_premium', 'subscription'),
  ('m_yoxi', 'transport'),
  ('m_凪ramen_nagi', 'restaurant'),
  ('m_摩斯漢堡', 'restaurant'),
  ('m_摩斯漢堡', 'fast_food'),
  ('m_肯德基', 'restaurant'),
  ('m_肯德基', 'fast_food'),
  ('m_頂呱呱', 'restaurant'),
  ('m_頂呱呱', 'fast_food'),
  ('m_漢堡王', 'restaurant'),
  ('m_漢堡王', 'fast_food'),
  ('m_美而美', 'restaurant'),
  ('m_美而美', 'breakfast'),
  ('m_弘爺漢堡', 'restaurant'),
  ('m_弘爺漢堡', 'breakfast'),
  ('m_早安美芝城', 'restaurant'),
  ('m_早安美芝城', 'breakfast'),
  ('m_麥味登', 'restaurant'),
  ('m_麥味登', 'breakfast'),
  ('m_星巴克', 'restaurant'),
  ('m_星巴克', 'coffee'),
  ('m_85度c', 'restaurant'),
  ('m_85度c', 'coffee'),
  ('m_85度c', 'bakery'),
  ('m_cama_caf', 'restaurant'),
  ('m_cama_caf', 'coffee'),
  ('m_丹堤咖啡', 'restaurant'),
  ('m_丹堤咖啡', 'coffee'),
  ('m_怡客咖啡', 'restaurant'),
  ('m_怡客咖啡', 'coffee'),
  ('m_大苑子', 'restaurant'),
  ('m_大苑子', 'beverage'),
  ('m_迷客夏', 'restaurant'),
  ('m_迷客夏', 'beverage'),
  ('m_萬波', 'restaurant'),
  ('m_萬波', 'beverage'),
  ('m_老虎堂', 'restaurant'),
  ('m_老虎堂', 'beverage'),
  ('m_清心福全', 'restaurant'),
  ('m_清心福全', 'beverage'),
  ('m_coco都可', 'restaurant'),
  ('m_coco都可', 'beverage'),
  ('m_一芳水果茶', 'restaurant'),
  ('m_一芳水果茶', 'beverage'),
  ('m_珍煮丹', 'restaurant'),
  ('m_珍煮丹', 'beverage'),
  ('m_得正', 'restaurant'),
  ('m_得正', 'beverage'),
  ('m_天仁茗茶', 'restaurant'),
  ('m_天仁茗茶', 'beverage'),
  ('m_春水堂', 'restaurant'),
  ('m_春水堂', 'beverage'),
  ('m_錢都涮涮鍋', 'restaurant'),
  ('m_錢都涮涮鍋', 'hot_pot'),
  ('m_石二鍋', 'restaurant'),
  ('m_石二鍋', 'hot_pot'),
  ('m_築間幸福鍋物', 'restaurant'),
  ('m_築間幸福鍋物', 'hot_pot'),
  ('m_鼎王麻辣鍋', 'restaurant'),
  ('m_鼎王麻辣鍋', 'hot_pot'),
  ('m_馬辣頂級麻辣鴛鴦火鍋', 'restaurant'),
  ('m_馬辣頂級麻辣鴛鴦火鍋', 'hot_pot'),
  ('m_鼎泰豐', 'restaurant'),
  ('m_三商巧福', 'restaurant'),
  ('m_度小月', 'restaurant'),
  ('m_貴族世家', 'restaurant'),
  ('m_壽司郎', 'restaurant'),
  ('m_壽司郎', 'japanese_food'),
  ('m_食其家', 'restaurant'),
  ('m_食其家', 'japanese_food'),
  ('m_吉野家', 'restaurant'),
  ('m_吉野家', 'japanese_food'),
  ('m_丸龜製麵', 'restaurant'),
  ('m_丸龜製麵', 'japanese_food'),
  ('m_爭鮮', 'restaurant'),
  ('m_爭鮮', 'japanese_food'),
  ('m_爭鮮', 'kaiten_sushi'),
  ('m_品田牧場', 'restaurant'),
  ('m_品田牧場', 'japanese_food'),
  ('m_王品台塑牛排', 'restaurant'),
  ('m_王品台塑牛排', 'steakhouse'),
  ('m_西堤牛排', 'restaurant'),
  ('m_西堤牛排', 'steakhouse'),
  ('m_原燒', 'restaurant'),
  ('m_原燒', 'yakiniku'),
  ('m_藝奇', 'restaurant'),
  ('m_舒果', 'restaurant'),
  ('m_舒果', 'vegetarian'),
  ('m_就饗鐵板燒', 'restaurant'),
  ('m_就饗鐵板燒', 'teppanyaki'),
  ('m_金咕韓式原塊烤肉', 'restaurant'),
  ('m_金咕韓式原塊烤肉', 'korean_bbq'),
  ('m_瓦城', 'restaurant'),
  ('m_瓦城', 'thai_food'),
  ('m_非常泰', 'restaurant'),
  ('m_非常泰', 'thai_food'),
  ('m_大心', 'restaurant'),
  ('m_大心', 'thai_food'),
  ('m_1010湘', 'restaurant'),
  ('m_十食湘', 'restaurant'),
  ('m_饗食天堂', 'restaurant'),
  ('m_饗食天堂', 'buffet'),
  ('m_漢來海港', 'restaurant'),
  ('m_漢來海港', 'buffet'),
  ('m_涓豆腐', 'restaurant'),
  ('m_涓豆腐', 'korean_bbq'),
  ('m_涓豆腐', 'hot_pot'),
  ('m_老四川', 'restaurant'),
  ('m_老四川', 'hot_pot'),
  ('m_達美樂', 'restaurant'),
  ('m_達美樂', 'pizza'),
  ('m_達美樂', 'delivery'),
  ('m_必勝客', 'restaurant'),
  ('m_必勝客', 'pizza'),
  ('m_必勝客', 'delivery'),
  ('m_鬍鬚張魯肉飯', 'restaurant'),
  ('m_欣葉台菜', 'restaurant'),
  ('m_悟饕池上便當', 'restaurant'),
  ('m_悟饕池上便當', 'bento'),
  ('m_我家牛排', 'restaurant'),
  ('m_我家牛排', 'steakhouse'),
  ('m_添好運', 'restaurant'),
  ('m_添好運', 'dim_sum'),
  ('m_樺達奶茶', 'restaurant'),
  ('m_樺達奶茶', 'beverage'),
  ('m_ok超商', 'chain_store'),
  ('m_美廉社', 'chain_store'),
  ('m_寶雅', 'health_beauty'),
  ('m_小三美日', 'health_beauty'),
  ('m_元祖', 'bakery'),
  ('m_亞尼克', 'bakery'),
  ('m_晶英酒店', 'lodging'),
  ('m_老爺酒店', 'lodging'),
  ('m_君品酒店', 'lodging'),
  ('m_翰品酒店', 'lodging'),
  ('m_兆品酒店', 'lodging'),
  ('m_福容大飯店', 'lodging'),
  ('m_六福萬怡酒店', 'lodging'),
  ('m_藏壽司', 'restaurant'),
  ('m_藏壽司', 'chain_store'),
  ('m_藏壽司', 'japanese_food'),
  ('m_路易莎咖啡', 'restaurant'),
  ('m_路易莎咖啡', 'coffee'),
  ('m_路易莎咖啡', 'chain_store'),
  ('m_小北百貨', 'general_retail');
